### ISSUE TITLE
can't get into digitizer via blueeeeeeeeeeeeeeeeeeeeeeeeeee tooth! Can not use!!!

### ISSUE THREAD

**Issue by 243750496** [jbedo/boogiesync-tablet#10]
what's wrong with my pad i can get mouse moved with usb insert with using usbdriver.py

python2 can get good resoponse but python3 not , but python2 with sudo command still failed ,but the python3 with sudo command can get mouse moved

```
cc@CC:~/boogiesync-tablet-master$ python blue.py
No device specified.  Searching all nearby bluetooth devices for
the boogie board sync input
connecting to "HID over SPP" on 00:17:E9:88:AA:D2
connected
good response
Traceback (most recent call last):
  File "blue.py", line 69, in <module>
    ui = UInput(cap, name='boogie-board-sync')
  File "/usr/local/lib/python2.7/dist-packages/evdev/uinput.py", line 136, in __init__
    _uinput.create(self.fd, name, vendor, product, version, bustype, absinfo)
IOError: [Errno 22] Invalid argument
cc@CC:~/boogiesync-tablet-master$ python3 blue.py
No device specified.  Searching all nearby bluetooth devices for
the boogie board sync input
couldn't find the boogie board sync
cc@CC:~/boogiesync-tablet-master$ python3 blue.py
No device specified.  Searching all nearby bluetooth devices for
the boogie board sync input
connecting to "HID over SPP" on 00:17:E9:88:AA:D2
connected

```

```

cc@CC:~/boogiesync-tablet-master$ python usb-driver.py
Traceback (most recent call last):
  File "usb-driver.py", line 10, in <module>
    if dev.is_kernel_driver_active(1):
  File "/home/cc/.local/lib/python2.7/site-packages/usb/core.py", line 1061, in is_kernel_driver_active
    self._ctx.managed_open()
  File "/home/cc/.local/lib/python2.7/site-packages/usb/core.py", line 102, in wrapper
    return f(self, *args, **kwargs)
  File "/home/cc/.local/lib/python2.7/site-packages/usb/core.py", line 120, in managed_open
    self.handle = self.backend.open_device(self.dev)
  File "/home/cc/.local/lib/python2.7/site-packages/usb/backend/libusb1.py", line 786, in open_device
    return _DeviceHandle(dev)
  File "/home/cc/.local/lib/python2.7/site-packages/usb/backend/libusb1.py", line 643, in __init__
    _check(_lib.libusb_open(self.devid, byref(self.handle)))
  File "/home/cc/.local/lib/python2.7/site-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 13] Access denied (insufficient permissions)
cc@CC:~/boogiesync-tablet-master$ python3 usb-driver.py
Traceback (most recent call last):
  File "usb-driver.py", line 10, in <module>
    if dev.is_kernel_driver_active(1):
  File "/usr/local/lib/python3.5/dist-packages/usb/core.py", line 1061, in is_kernel_driver_active
    self._ctx.managed_open()
  File "/usr/local/lib/python3.5/dist-packages/usb/core.py", line 102, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/usb/core.py", line 120, in managed_open
    self.handle = self.backend.open_device(self.dev)
  File "/usr/local/lib/python3.5/dist-packages/usb/backend/libusb1.py", line 786, in open_device
    return _DeviceHandle(dev)
  File "/usr/local/lib/python3.5/dist-packages/usb/backend/libusb1.py", line 643, in __init__
    _check(_lib.libusb_open(self.devid, byref(self.handle)))
  File "/usr/local/lib/python3.5/dist-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 13] Access denied (insufficient permissions)
cc@CC:~/boogiesync-tablet-master$ sudo python usb-driver.py
[sudo] password for cc: 
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
Payload sent
Traceback (most recent call last):
  File "usb-driver.py", line 57, in <module>
    ui = UInput(cap, name='boogie-board-sync-pen')
  File "/usr/local/lib/python2.7/dist-packages/evdev/uinput.py", line 136, in __init__
    _uinput.create(self.fd, name, vendor, product, version, bustype, absinfo)
IOError: [Errno 22] Invalid argument
cc@CC:~/boogiesync-tablet-master$ sudo python3 usb-driver.py
Payload sent
^Ccc@CC:~/boogiesync-tablet-master$ 
```

**Comment by jbedo** [comment]
The python2 failure looks like a problem in evdev. Evdev is working fine for your python3 installation, so that's why python3 works and not python2.  Not sure what's wrong with the bluetooth version, can you try connecting with python3 via usb and then see if the bluetooth works? Don't turn off the boogie board between usb & bluetooth.

Ps, on holidays atm so my responses might be delayed.

**Comment by 243750496** [comment]
can you try connecting with python3 via usb and then see if the bluetooth works?
i didn't quite understand  , could explain it more deeply and the steps?
what do it means by connect via usb and both blootooth through py3???

**Comment by jbedo** [comment]
Sorry for the confusion, I'd like to find out if bluetooth works after you successfully use it as a digitiser via usb. So just connect via usb then quit, unplug the usb, and try via bluetooth. Just trying to figure out if the bluetooth connection works after the tablet has been set to digitiser mode via usb.

**Comment by 243750496** [comment]
```
cc@CC:~/boogiesync-tablet-master$ sudo python3 usb-driver.py
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
Payload sent
^Ccc@CC:~/boogiesync-tablet-master$ sudo python3 blue.py 00:17:E9:88:AA:D2
Searching for boogie board sync on 00:17:E9:88:AA:D2
connecting to "HID over SPP" on 00:17:E9:88:AA:D2
Traceback (most recent call last):
  File "<string>", line 3, in connect
_bluetooth.error: (111, 'Connection refused')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "blue.py", line 36, in <module>
    sock.connect((host, port))
  File "<string>", line 5, in connect
bluetooth.btcommon.BluetoothError: (111, 'Connection refused')

```


Q1：Did u mean disconnect after the unplug and then type the sudo python3 blue.py 00:17:E9:88:AA:D2 at the fastest speed without the sync powered off  then it show the code up there, 
why failed?all faield?or succese in some step?

Q2:if i tried to connecte it after succeed in digitiser then poweroff and press save and turn on then all issues comes with nothing changed like before , 

BTW Q3: i havn't add it to bluetooth in system at this time firstly
![bluetooth](https://cloud.githubusercontent.com/assets/6311930/21672796/ad912a12-d35f-11e6-8e3c-900b4fcd07d1.png)
 , do this step correct???

**Comment by jbedo** [comment]
I never did work out why the payload would fail for so many times before
succeeding, but this is what happens on my boogie board too. It's not a big
priority because it does eventually succeed and works as a tablet. You don't
need to pair with the boogie board before hand, so you're doing that correctly.

Rereading your original log:

> cc@CC:~/boogiesync-tablet-master$ python blue.py
> No device specified.  Searching all nearby bluetooth devices for
> the boogie board sync input
> connecting to "HID over SPP" on 00:17:E9:88:AA:D2
> connected
> good response
> Traceback (most recent call last):
>   File "blue.py", line 69, in <module>
>     ui = UInput(cap, name='boogie-board-sync')
>   File "/usr/local/lib/python2.7/dist-packages/evdev/uinput.py", line 136, in __init__
>     _uinput.create(self.fd, name, vendor, product, version, bustype, absinfo)
> IOError: [Errno 22] Invalid argument

Looks like your python2 evdev is broken. Which OS are you using?

**Comment by 243750496** [comment]
Ubuntu  16.10

**Comment by 243750496** [comment]
？？？？why  there's no other comments? Have  u forget  it?

**Comment by jbedo** [comment]
I haven't forgotten it, I just haven't got around to installing ubuntu and trying to reproduce your problem. It looks like it's an os problem, rather than a problem in this code, so there's likely not a lot I can do about it anyway.

**Comment by 243750496** [comment]
So the only solution is to change os?

**Comment by jbedo** [comment]
No I didn't mean that, I meant the problem is well outside the scope of this project and that to fix it would essentially be debugging your particular installation of python. There is no guarantee I'll be able to even reproduce the problem on a fresh install of Ubuntu anyway. If I get enough spare time I may give this a go, but I suggest you also look elsewhere to figure out what's wrong with your evdev.

**Comment by jbedo** [comment]
Think this is resolved.
