### ISSUE TITLE
IOError: [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by 243750496** [jbedo/boogiesync-tablet#7]
```


cc@CC:~$ pip install --pre pyusb
Collecting pyusb
Downloading PyUSB-1.0.0.tar.gz (52kB)
100% |████████████████████████████████| 61kB 228kB/s
Building wheels for collected packages: pyusb
Running setup.py bdist_wheel for pyusb ... done
Stored in directory: /home/cc/.cache/pip/wheels/18/b0/b8/83d67cc7a3b50866f908ca1104b553f7807e1e767ddf373427
Successfully built pyusb
Installing collected packages: pyusb
Successfully installed pyusb
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
cc@CC:~$ pip install --upgrade pip
Collecting pip
Downloading pip-9.0.1-py2.py3-none-any.whl (1.3MB)
100% |████████████████████████████████| 1.3MB 684kB/s
Installing collected packages: pip
Successfully installed pip-9.0.1
cc@CC:~$ pip install --pre pyusb
Requirement already satisfied: pyusb in ./.local/lib/python2.7/site-packages
cc@CC:~$ pip install --pre evdev
Collecting evdev
Downloading evdev-0.6.4.tar.gz
Building wheels for collected packages: evdev
Running setup.py bdist_wheel for evdev ... done
Stored in directory: /home/cc/.cache/pip/wheels/64/4e/61/20afc41b2f932f4e520fff9f8d70c063eab38c21dc0e5d9d62
Successfully built evdev
Installing collected packages: evdev
Exception:
Traceback (most recent call last):
File "/home/cc/.local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
status = self.run(options, args)
File "/home/cc/.local/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
prefix=options.prefix_path,
File "/home/cc/.local/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
**kwargs
File "/home/cc/.local/lib/python2.7/site-packages/pip/req/req_install.py", line 851, in install
self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
File "/home/cc/.local/lib/python2.7/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
isolated=self.isolated,
File "/home/cc/.local/lib/python2.7/site-packages/pip/wheel.py", line 345, in move_wheel_files
clobber(source, lib_dir, True)
File "/home/cc/.local/lib/python2.7/site-packages/pip/wheel.py", line 316, in clobber
ensure_dir(destdir)
File "/home/cc/.local/lib/python2.7/site-packages/pip/utils/init.py", line 83, in ensure_dir
os.makedirs(path)
File "/usr/lib/python2.7/os.py", line 157, in makedirs
mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/evdev-0.6.4.dist-info'
cc@CC:~$ sudo pip install --pre evdev
The directory '/home/cc/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/cc/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting evdev
Installing collected packages: evdev
Successfully installed evdev-0.6.4
cc@CC:~$ sudo pip install --pre evdev
The directory '/home/cc/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/cc/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: evdev in /usr/local/lib/python2.7/dist-packages
cc@CC:~$ sudo pip install pybluez
[sudo] password for cc: 
The directory '/home/cc/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/cc/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting pybluez
  Downloading PyBluez-0.22.zip (109kB)
    100% |████████████████████████████████| 112kB 34kB/s 
Installing collected packages: pybluez
  Running setup.py install for pybluez ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-b5_THW/pybluez/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-eW5_bR-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/bluetooth
    copying bluetooth/ble.py -> build/lib.linux-x86_64-2.7/bluetooth
    copying bluetooth/btcommon.py -> build/lib.linux-x86_64-2.7/bluetooth
    copying bluetooth/msbt.py -> build/lib.linux-x86_64-2.7/bluetooth
    copying bluetooth/widcomm.py -> build/lib.linux-x86_64-2.7/bluetooth
    copying bluetooth/bluez.py -> build/lib.linux-x86_64-2.7/bluetooth
    copying bluetooth/__init__.py -> build/lib.linux-x86_64-2.7/bluetooth
    copying bluetooth/osx.py -> build/lib.linux-x86_64-2.7/bluetooth
    running build_ext
    building 'bluetooth._bluetooth' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/bluez
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I./port3 -I/usr/include/python2.7 -c bluez/btmodule.c -o build/temp.linux-x86_64-2.7/bluez/btmodule.o
    In file included from bluez/btmodule.c:20:0:
    bluez/btmodule.h:5:33: fatal error: bluetooth/bluetooth.h: No such file or directory
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-b5_THW/pybluez/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-eW5_bR-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-b5_THW/pybluez/
cc@CC:~$ sudo pip install --pre pybluez
The directory '/home/cc/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/cc/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting pybluez
  Downloading PyBluez-0.22.zip (109kB)
    100% |████████████████████████████████| 112kB 174kB/s 
Installing collected packages: pybluez
  Running setup.py install for pybluez ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-HA3wRf/pybluez/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-IpLX6l-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/bluetooth
    copying bluetooth/ble.py -> build/lib.linux-x86_64-2.7/bluetooth
    copying bluetooth/btcommon.py -> build/lib.linux-x86_64-2.7/bluetooth
    copying bluetooth/msbt.py -> build/lib.linux-x86_64-2.7/bluetooth
    copying bluetooth/widcomm.py -> build/lib.linux-x86_64-2.7/bluetooth
    copying bluetooth/bluez.py -> build/lib.linux-x86_64-2.7/bluetooth
    copying bluetooth/__init__.py -> build/lib.linux-x86_64-2.7/bluetooth
    copying bluetooth/osx.py -> build/lib.linux-x86_64-2.7/bluetooth
    running build_ext
    building 'bluetooth._bluetooth' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/bluez
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I./port3 -I/usr/include/python2.7 -c bluez/btmodule.c -o build/temp.linux-x86_64-2.7/bluez/btmodule.o
    In file included from bluez/btmodule.c:20:0:
    bluez/btmodule.h:5:33: fatal error: bluetooth/bluetooth.h: No such file or directory
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-HA3wRf/pybluez/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-IpLX6l-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-HA3wRf/pybluez/
cc@CC:~$ sudo apt-get install libbluetooth-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  linux-headers-4.4.0-21 linux-headers-4.4.0-21-generic
  linux-image-4.4.0-21-generic linux-image-extra-4.4.0-21-generic
Use 'sudo apt autoremove' to remove them.
The following NEW packages will be installed:
  libbluetooth-dev
0 upgraded, 1 newly installed, 0 to remove and 75 not upgraded.
Need to get 145 kB of archives.
After this operation, 570 kB of additional disk space will be used.
Get:1 http://cn.archive.ubuntu.com/ubuntu xenial/main amd64 libbluetooth-dev amd64 5.37-0ubuntu5 [145 kB]
Fetched 145 kB in 2s (50.9 kB/s)                          
Selecting previously unselected package libbluetooth-dev.
(Reading database ... 315080 files and directories currently installed.)
Preparing to unpack .../libbluetooth-dev_5.37-0ubuntu5_amd64.deb ...
Unpacking libbluetooth-dev (5.37-0ubuntu5) ...
Setting up libbluetooth-dev (5.37-0ubuntu5) ...
cc@CC:~$ sudo pip install pybluez
The directory '/home/cc/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/cc/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting pybluez
  Downloading PyBluez-0.22.zip (109kB)
    100% |████████████████████████████████| 112kB 353kB/s 
Installing collected packages: pybluez
  Running setup.py install for pybluez ... done
Successfully installed pybluez-0.22
cc@CC:~$ sudo pip install --pre pybluez
The directory '/home/cc/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/cc/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: pybluez in /usr/local/lib/python2.7/dist-packages

```
cc@CC:~/boogiesync-tablet-master$ ./usb-driver.py
Traceback (most recent call last):
  File "./usb-driver.py", line 10, in <module>
    if dev.is_kernel_driver_active(1):
  File "/home/cc/.local/lib/python2.7/site-packages/usb/core.py", line 1061, in is_kernel_driver_active
    self._ctx.managed_open()
  File "/home/cc/.local/lib/python2.7/site-packages/usb/core.py", line 102, in wrapper
    return f(self, *args, **kwargs)
  File "/home/cc/.local/lib/python2.7/site-packages/usb/core.py", line 120, in managed_open
    self.handle = self.backend.open_device(self.dev)
  File "/home/cc/.local/lib/python2.7/site-packages/usb/backend/libusb1.py", line 786, in open_device
    return _DeviceHandle(dev)
  File "/home/cc/.local/lib/python2.7/site-packages/usb/backend/libusb1.py", line 643, in __init__
    _check(_lib.libusb_open(self.devid, byref(self.handle)))
  File "/home/cc/.local/lib/python2.7/site-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 13] Access denied (insufficient permissions)

cc@CC:~/boogiesync-tablet-master$ sudo ./usb-driver.py
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
Payload sent
Traceback (most recent call last):
  File "./usb-driver.py", line 57, in <module>
    ui = UInput(cap, name='boogie-board-sync-pen')
  File "/usr/local/lib/python2.7/dist-packages/evdev/uinput.py", line 136, in __init__
    _uinput.create(self.fd, name, vendor, product, version, bustype, absinfo)
IOError: [Errno 22] Invalid argument

cc@CC:~/boogiesync-tablet-master$ ./blue.py 00:17:E9:88:AA:D2
Searching for boogie board sync on 00:17:E9:88:AA:D2
connecting to "HID over SPP" on 00:17:E9:88:AA:D2
connected
good response
Traceback (most recent call last):
  File "./blue.py", line 69, in <module>
    ui = UInput(cap, name='boogie-board-sync')
  File "/usr/local/lib/python2.7/dist-packages/evdev/uinput.py", line 136, in __init__
    _uinput.create(self.fd, name, vendor, product, version, bustype, absinfo)
IOError: [Errno 22] Invalid argument

cc@CC:/boogiesync-tablet-master$ sudo ./blue.py 00:17:E9:88:AA:D2
[sudo] password for cc:
Searching for boogie board sync on 00:17:E9:88:AA:D2
connecting to "HID over SPP" on 00:17:E9:88:AA:D2
connected
good response
Traceback (most recent call last):
File "./blue.py", line 69, in
ui = UInput(cap, name='boogie-board-sync')
File "/usr/local/lib/python2.7/dist-packages/evdev/uinput.py", line 136, in init
_uinput.create(self.fd, name, vendor, product, version, bustype, absinfo)
IOError: [Errno 22] Invalid argument
cc@CC:/boogiesync-tablet-master$

**Comment by 243750496** [comment]
sloved by using pip3 and install all the depends then type python3 blue.py ADDRESS
