### ISSUE TITLE
can not knock into digitizer mode with bluetooth

### ISSUE THREAD

**Issue by 243750496** [jbedo/boogiesync-tablet#9]
#8 

jbedo ：
ok that's pretty interesting, because with python 2 it seems to send the payload and get a good response, but die trying to create a uinput device. Are you using python 2 or 3 with usb?

**cc@CC:~/boogiesync-tablet-master$ sudo python usb-driver.py**
```
[sudo] password for cc:
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
payload transfer failed, retrying
Payload sent
Traceback (most recent call last):
File "usb-driver.py", line 57, in
ui = UInput(cap, name='boogie-board-sync-pen')
File "/usr/local/lib/python2.7/dist-packages/evdev/uinput.py", line 136, in init
_uinput.create(self.fd, name, vendor, product, version, bustype, absinfo)
IOError: [Errno 22] Invalid argument
```
**cc@CC:~/boogiesync-tablet-master$ sudo python3 usb-driver.py
Payload sent**

**with python3 i curser moved while pen moved , btw Q: Do the sudo is a must while trying to connect by using usb Q2: what about bluetooth(why bluetooth doesn't need sudo command???)**

**Comment by jbedo** [comment]
Sudo is not a must, if your user has permissions to the usb subsystem then it should work as a plain user. Bluetooth also doesn't need sudo, it just needs access to bluez.

**Comment by 243750496** [comment]
but why cant knock into digitizer by using bluetooth(with python3 ) mode as #8 said before
btw python2 can get good connection but failed at the end python3 success but not said it get good connection
@jbedo

**Comment by 243750496** [comment]
i am waiting ur reply :) please dont foget my issue and give me a reply thx
